### ISSUE TITLE
Gene definition

### ISSUE THREAD

**Issue by mumichae** [RNAcentral/rnacentral-import-pipeline#100]
It seems there is no real gene definition in the GTF (at least for human). The attributes column contains a `Name` that encompasses multiple exons and transcripts. However in the ID mapping file, there are multiple cases where a single external gene ID maps to multiple URS. Examples: MEF2C-AS1, LINC00929, SNHG7

So do URS map to transcripts? If so, why is there the distinction between URS (`Name` in attributes) and transcript IDs (`ID` in attributes)?

**Comment by blakesweeney** [comment]
You are correct that URS maps to transcripts at the momement and we do not have RNA genes yet. Each URS is a Unique RNA Sequence, which means that generally each transcript gets its own URS. Because of this it is common that a single external gene maps to more than one URS as they often have more than one transcript.

We are working on building genes, but that is an ongoing project but the results are not ready for general use. 

As for the `Name` vs `ID` attributes, I create a unique id for each exon (the `ID` attribute) and have a `Name` attribute that is the URS for all exons. I think that is the best way to represent RNAcentral data in gff format. If not I'm open to some suggestions for a better structure or documentation.

**Comment by mumichae** [comment]
I see, that makes sense!

However, I'm still confused about the difference between the `Name` vs `ID` attributes for transcripts. E.g for `URS00008C1902_9606` there are two transcript entries with `ID=URS00008C1902_9606.1` and `ID=URS00008C1902_9606.2` respectively. How do these relate?

**Comment by blakesweeney** [comment]
There probably shouldn't be duplicate ids like you found, I need to look into that. Are you saying that if a URS has more than one location there are duplicates ids? That seems like a bug.

 As for the off by one locations, I think I've fixed that in the latest release. It is a known issue I've been working at. Thanks for pointing it out!

**Comment by mumichae** [comment]
Are you referring to release 18? I double-checked, and I could find these examples in a fresh download of the GFF.

These examples were just the first I could find, but there seem to be quite a few

```
$ zcat homo_sapiens.GRCh38.gff3.gz | grep -P '\ttranscript\t' | cut -f9 | cut -f1 -d';' | sort | uniq -c | less

      2 Name=URS0000000055_9606
      1 Name=URS0000000096_9606
      1 Name=URS0000000098_9606
...
   12 Name=URS0000000FA0_9606
      1 Name=URS0000000FAA_9606
      2 Name=URS0000000FC4_9606
      1 Name=URS0000001021_9606
      1 Name=URS00000010A5_9606
     16 Name=URS0000001162_9606

...
```

For lncRNA there never seem to be more than 2 duplicates per chromosome and are only 1 base off. The larger duplicate counts come from piRNA, but in those cases, the same name maps to regions on different chromosomes.

Finally, the naming conventions are different between `Name` and `ID` for transcript. For example, `Name=URS00008B37EC_9606;ID=URS00008B37EC_9606.3`. In that case are `URS00008B37EC_9606.3` and `URS00008B37EC_9606.4` just different versions of the same transcript that should have been cleaned up?

**Comment by blakesweeney** [comment]
Hi, sorry for being unclear. I was refering to release 19, which we are currently finishing. When I looked into it it seemed to be all lncipedia sequences were showing this issue. The release will be out in the near future and should have some fixes for these issues. Sorry for the confusion.

**Comment by mumichae** [comment]
OK, thanks a lot for the info! Will be looking forward to the new version :smiley:
