### ISSUE TITLE
Upper case all sequences when importing 

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/rnacentral-import-pipeline#130]
Seems that when we imported lncbook data we did not uppercase all sequences. Consider:

https://rnacentral.org/rna/URS0001BE2550/9606

This provides some warnings about containing T's when it shouldn't. Checking the sequence in the database shows that it is a mix of lower/uppercase sequences, which is likely causing the issue. It should always be uppercase.

**Comment by afg1** [comment]
This isn't caused by lncbook I think. The lncbook sequence turns up here: 

https://rnacentral.org/rna/URS0000D5C4ED/9606

Where it has the correct linkage with everything, and the sequence correctly contains only U's when copied as RNA

I think from poking about a bit that the lowercase sequence originally came via MalaCards/GeneCards/LncBookV1. There are two entries that are active in xref with that URS. Unless we can manually change the sequences and MD5s, I'll have a look at reimporting those databases.

**Comment by afg1** [comment]
Following re-import of CRW, GeneCards & MalaCards, I think this is fixed. The original ID is showing up in the test site as expected:
https://test.rnacentral.org/rna/URS0000D5C4ED/9606
And the original now says the links were removed from the expert database:
https://test.rnacentral.org/rna/URS0001BE2550/9606

One thing I'm not sure about - there seems to be 2x linkages to LncBook, MalaCards and GeneCards. It looks to me like it's just multiple IDs for the same sequence, but is it something to worry about or not. I haven't run search export yet if that would change things

**Comment by blakesweeney** [comment]
The duplicated links are likely an issue. I think we can close this one and I'll open another one for duplicated links.
