### ISSUE TITLE
Gene types

### ISSUE THREAD

**Issue by mumichae** [RNAcentral/rnacentral-import-pipeline#96]
Hello,

I came across the gene type 'sRNA' (e.g. in gene  [URS0001BF7BA4_9606](https://rnacentral.org/rna/URS0001BF7BA4/9606)) and was wondering what biotype it corresponds to. At first I assumed it to be short ncRNA, however, the genes are generally longer than 200nt.

I couldn't find any more information on this. Is there something I've been missing?

Best,
Michaela

P.S. I wasn't quite sure where to post this, so please let me know if I should move this conversation elsewhere.

**Comment by blakesweeney** [comment]
Hi Michaela,

You can reach out to us where you like, we are happy to answer questions publically or via email. I'm responding here since it might be useful to others and I don't want to give the impression we ignore users. 

As for the RNA type you noticied, sRNA, this is actually an outdated term from previous versions of RNAcentral RNA type annotations. The term is no longer used by INSDC, which defined it, as far as I can see. So I would say that annotation is a mistake. I've opened an issue (https://github.com/RNAcentral/rnacentral-webcode/issues/560) to fix the summary text we generate. Also the sequence you pointed out should probably be called an lncRNA but isn't so I'll look into that issue as well. Thanks for reaching out and let us know if we can help!
